# Copyright 2020 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# https://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.


ListenUDP *:1812
ListenUDP *:1813

LogLevel 5
LogDestination file:///dev/stdout

LoopPrevention On

tls eapol {
    CACertificatePath /etc/ssl/certs/cacerts
    CertificateFile /etc/ssl/certs/cert.pem
    CertificateKeyFile /etc/ssl/certs/key.pem
}

client local-docker-inbound {
    host 0.0.0.0/0
    type UDP
    secret RADIUS_SECRET
}

server radsec-gfe {
    host RADSEC_DESTINATION_IP
    type tls
    tls eapol
    port RADSEC_DESTINATION_PORT
    StatusServer on
}

realm   * {
    server radsec-gfe
    accountingServer radsec-gfe
}
